### ISSUE TITLE
管理员无法修改别人代码的源码可见性

### ISSUE THREAD

**Issue by t123yh** [Codgic/codgic-web-legacy#13]

**Comment by codgician** [comment]
我个人本来就是这么设计的，自己的源码是否开源应该自己来决定啊。。。看看你们的意见吧。

**Comment by xiawenke** [comment]
我觉得自己源码的开源性质的确要由自己来决定
但管理员也因有权修改源码性质 准确的说来是请求对方修改源码性质 要经过对方同意来更改…吧
