### ISSUE TITLE
将服务器上的修改合并至源代码库。

### ISSUE THREAD

**Issue by t123yh** [Codgic/codgic-web-legacy#26]
具体的修改有：
* 增加一堆语言。具体修改的文件：`/lib/lang.php`。
* 增加 BASIC 代码编辑器支持。具体修改的文件：`/problempage.php`，`/sourcecode.php`，`/assets/js/CodeMirror/mode/basic.js`。

**Comment by codgician** [comment]
对于语言 (lang.php) 的修改等到新daemon开源后再添加。
