### ISSUE TITLE
xss漏洞

### ISSUE THREAD

**Issue by CANGJINKONG** [Codgic/codgic-web-legacy#32]
https://cwoj.org/board.php?problem_id=1070%27%22()%26%25%3Cacx%3E%3CScRiPt%20%3EALERT(%27FUCKT123YH%27);%20%3C/ScRiPt%3E

**Comment by ice1000** [comment]
看我发现了什么，URL里面有一段奇怪的FUCKT123YH 😂

**Comment by codgician** [comment]
修复代码已上传服务器，GitHub上随下一次PR提交。谢谢！
