### ISSUE TITLE
题目页面文字没有转义处理

### ISSUE THREAD

**Issue by t123yh** [Codgic/codgic-web-legacy#5]
例如题目1000描述中 `#include <iostream>` 的 `<iostream>` 无法显示

**Comment by codgician** [comment]
由于目前题目中存在可能会遇到需要设置字体样式之类等不得不插入HTML Code的状况，并考虑到管理员素质较高，暂时无法解决这项问题。
不过我的确有把题目页面文字，新闻页面文字<s>全面转向markdown的想法</s>将会加入wysiwyg富文本编辑器，在届时将会有转义处理以确保安全。

**Comment by t123yh** [comment]
不建议使用 WYSIWYG 编辑器，会导致文本结构 **异常** 混乱。并且 Markdown 可以使用 HTML 标签，只需要净化处理即可。

**Comment by codgician** [comment]
HTML Purifier has been introduced.
